language: objective-c

before_install:
    - gem update --system
    - gem install ios_ci
    - gem install cocoapods
    - brew install ios-sim

script: ios_ci cedar --source-root $TRAVIS_BUILD_DIR --workspace BloodMagic.xcworkspace --scheme BloodMagic --build-path build/Products

notifications:
  email:
    - 1101.debian@gmail.com
