language: objective-c

before_install:
    - sudo gem update --system
    - sudo gem install ios_ci
    - sudo gem update cocoapods
    - brew install ios-sim

script: ios_ci cedar --source-root $TRAVIS_BUILD_DIR --workspace BloodMagic.xcworkspace --scheme BloodMagic --build-path build/Products

